server:
  port: 8888

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        # 强制网关用127.0.0.1注册，解决IP异常问题
        ip: 127.0.0.1
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: notice-service
          uri: lb://notice-service
          predicates:
            - Path=/api/notice/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true