server:
  port: 8085

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1       # 强制固定IP，不出现169.254
        server-addr: localhost:8848
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_micro?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto