server:
  port: 8082

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1      # 必须加！解决169.254问题
        server-addr: localhost:8848
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_micro?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto